#!/bin/bash

module load fre/bronx-18

#: jobtype = all, meta, data
jobtype=$1
#: set default to all, will use nccmp -m -d
if [ $# -eq 0 ] ; then jobtype='all' ; fi

#: workdir with rt*.log results.  set by runscript
testdir=CHANGEMETESTDIR
rtdir=CHANGEMERTDIR

#: check all test files in tests/tests directory
testlist=( $(ls $testdir) )

for rt_test in ${testlist[@]} ; do
    
    echo $rt_test

    #: get rt_0##_fv3_ccpp_${rt_test}_prod.log
    rt_log=$( ls $rtdir/rt*.log | grep "${rt_test}_prod.log" | grep "rt" )

    #: check if rt_log exists
    if [[ $rt_log == '' || ! -f $rt_log ]] ; then
	echo "$rt_test  NOT FOUND"
	continue
    fi

    #: get baseline dir and my working dir
    refdir=$( grep "baseline dir" $rt_log | awk '{print $4}' )
    mydir=$(  grep "working dir"  $rt_log | awk '{print $4}' )   
    
    #: prep output file
    outputfile=NCCMP_$rt_test
    if [ -f $outputfile ] ; then rm $outputfile ; fi
    touch -a $outputfile
    echo "1 NEWDATA $mydir"  >> $outputfile
    echo "2 REFDATA $refdir" >> $outputfile
    
    #: read files to compare in $rt_log
    while read myline ; do

	#: get netcdf history or restart file
	if [[ $myline == *"Comparing"* ]] ; then
	    myfile=$( echo $myline | awk '{print $2}' )
	    echo -e "\n*******************************" >> $outputfile
	    echo $myline                                >> $outputfile
	fi

	if [[ $myline == *"NOT OK"* ]] ; then
	    if [ $jobtype == 'meta' ] ; then    
		nccmp -c 1 -f -m $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    elif [ $jobtype == 'data' ] ; then
		nccmp -c 1 -f -d $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    else
		nccmp -c 1 -f -d -m $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    fi 
	fi
	
	sed -i 's/DIFFER :/   /g' $outputfile
	echo -e "\t\t $myline"

    done < $rt_log

done 
