#!/bin/bash


#: jobtype = all, meta, data.  default to all
jobtype='all'

while getopts "hmdt:" myopts ; do
    case ${myopts} in 
	m) jobtype='meta' ;;
	d) jobtype='data' ;;
	t) 
	    IFS=,;  set -f
	    testlist=(${OPTARG})  
	    set +f ; unset IFS ;;	
	h) 
	    echo -e "\t -m metadata (default set to all)"
	    echo -e "\t -d data (default set to all)"
	    echo -e "\t -t list of rt_*.log files separated by , no space between ,"
    esac
done

for rt_test in ${testlist[@]} ; do
    
    #: get rt_0##_fv3_ccpp_${rt_test}_prod.log
    rt_log=$rt_test

    #: check if rt_log exists
    if [[ $rt_log == '' || ! -f $rt_log ]] ; then
	echo "$rt_test  NOT FOUND"
	continue
    fi

    echo "$rt_test"
    
    #: get baseline dir and my working dir
    refdir=$( grep "baseline dir" $rt_log | awk '{print $4}' )
    mydir=$(  grep "working dir"  $rt_log | awk '{print $4}' )   
    
    #: prep output file
    outputfile=NCCMP_$rt_test
    if [ -f $outputfile ] ; then rm $outputfile ; fi
    touch -a $outputfile
    echo "1 NEWDATA $mydir"  >> $outputfile
    echo "2 REFDATA $refdir" >> $outputfile
    
    #: read files to compare in $rt_log
    while read myline ; do

	#: get netcdf history or restart file
	if [[ $myline == *"Comparing"* ]] ; then
	    myfile=$( echo $myline | awk '{print $2}' )
	    echo -e "\n*******************************" >> $outputfile
	    echo $myline                                >> $outputfile
	fi

	if [[ $myline == *"NOT OK"* ]] ; then
	    if [ $jobtype == 'meta' ] ; then    
		nccmp -c 1 -f -m $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    elif [ $jobtype == 'data' ] ; then
		nccmp -c 1 -f -d $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    else
		nccmp -c 1 -f -d -m $mydir/$myfile $refdir/$myfile >> $outputfile 2>&1
	    fi 
	fi
	
	sed -i 's/DIFFER :/   /g' $outputfile
	echo -e "\t\t $myline"

    done < $rt_log

done 
