name: run_on_schedule

on:
  push:
    branches:
      - master #nobranch
  pull_request:
    branches:
      - master #nobranch

jobs:

  ufs_fms_ci:
    runs-on:  ubuntu-latest
    needs: check_previous_run
    steps: 
      - name: checkout 
        uses: actions/checkout@v2

      - name: get NCEPLIB HASH (not the best way?)
        run: |
          git clone --branch build_libs https://github.com/mlee03/UFS_CI_TEST.git build_libs
          mv build_libs/LIB_HASHFILE . && rm -rf build_libs

  
      - name: cache ncep hashfile
        uses: actions/cache@v2
        with:
          path: hashfiles
          key: hashfile-${{GITHUB.RUN_ID}}
          restore-keys: hashfile-

      - name: mkdir hashfiles if it doens't exist
        run: mkdir -p hashfiles

      - name: update images and rebuild
        run: ./check.sh ${{secrets.DOCKER_USERNAME}} ${{secrets.DOCKER_PASSWORD}} 1

      - name: store LOG
        uses: actions/upload-artifact@v1
        with:
          name: logfile
          path: LOG

