name: run_on_schedule

on:
  schedule:
    - cron: '*/59 7-19 * * 1-5'

jobs:

  check_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2

      - name: cache workflow_status file
        uses: actions/cache@v2
        with:
          path: workflow_status
          key:  workflow_status2-${{GITHUB.RUN_ID}}_0
          restore-keys: workflow_status2-    

      - name: check if previous workflow is running
        run: |
          ./workflow.sh 'start' ${{GITHUB.RUN_ID}}
  
  ufs_fms_ci:
    runs-on:  ubuntu-latest
    needs: check_previous_run
    steps: 
      - name: checkout 
        uses: actions/checkout@v2

      - name: cache ncep hashfile
        uses: actions/cache@v2
        with:
          path: hashfiles
          key: hashfile-${{GITHUB.RUN_ID}}
          restore-keys: hashfile-

      - name: cache workflow_status file
        uses: actions/cache@v2
        with:
          path: workflow_status
          key:  workflow_status2-${{GITHUB.RUN_ID}}_1
          restore-keys: workflow_status2-    
  
      - name: mkdir hashfiles if it doens't exist
        run: mkdir -p hashfiles

      - name: update images and rebuild
        run: ./check.sh ${{secrets.DOCKER_USERNAME}} ${{secrets.DOCKER_PASSWORD}} 4

      - name: if fail edit workflow file
        if: ${{ failure() }}
        run: ./workflow.sh 'failed' ${{GITHUB.RUN_ID}}

      - name: store LOG
        uses: actions/upload-artifact@v1
        with:
          name: logfile
          path: LOG

  end :
    runs-on: ubuntu-latest
    needs: ufs_fms_ci
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get workflow_status file
        uses: actions/cache@v2
        with:
          path: workflow_status
          key:  workflow_status2-${{GITHUB.RUN_ID}}_3
          restore-keys: workflow_status2-

      - name: check if previous workflow is running
        run: ./workflow.sh 'end' ${{GITHUB.RUN_ID}}                
